query Pokemons($options: PokemonsOptions){
  pokemons(options: $options) {
    edges {
      cursor
      node {
        id
        name
        dexes {
          id
          number
          name
        }
      }
    }
    pageInfo {
      pageCount
      totalCount
      hasNextPage
      hasPreviousPage
    }
  }
}